-d C:\Users\Panagiotis\Documents\GitHub\RiscY\riscy25k\impl\gwsynthesis\riscy25k.vg
-p GW5A-25A-MBGA121N-1
-pn GW5A-LV25MG121NES
-cst C:\Users\Panagiotis\Documents\GitHub\RiscY\riscy25k\src\tang25k.cst
-cfg C:\Users\Panagiotis\Documents\GitHub\RiscY\riscy25k\impl\pnr\device.cfg
-sdc C:\Users\Panagiotis\Documents\GitHub\RiscY\riscy25k\src\timing25k.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 2
-route_option 2
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
