-d /home/iordana/Documents/GitHub/RiscY/RISCY/impl/gwsynthesis/RISCY.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /home/iordana/Documents/GitHub/RiscY/RISCY/src/tangnano9k.cst
-cfg /home/iordana/Documents/GitHub/RiscY/RISCY/impl/pnr/device.cfg
-sdc /home/iordana/Documents/GitHub/RiscY/RISCY/src/Tang_nano_9K_LCD.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 2
-route_option 1
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
