-d E:\gowin\RISCV\impl\gwsynthesis\RISCV.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst E:\gowin\RISCV\src\tangnano9k.cst
-cfg E:\gowin\RISCV\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
