-d E:\Projects\TangNano-9K-example-main\hdmi\impl\gwsynthesis\hdmi.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst E:\Projects\TangNano-9K-example-main\hdmi\src\hdmi.cst
-cfg E:\Projects\TangNano-9K-example-main\hdmi\impl\pnr\device.cfg
-sdc E:\Projects\TangNano-9K-example-main\hdmi\src\hdmi.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
