// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        CData/*0:0*/ top__DOT__reset;
        VL_OUT8(LCD_CLK,0,0);
        VL_OUT8(LCD_HYNC,0,0);
        VL_OUT8(LCD_SYNC,0,0);
        VL_OUT8(LCD_DEN,0,0);
        VL_OUT8(LCD_R,4,0);
        VL_OUT8(LCD_G,5,0);
        VL_OUT8(LCD_B,4,0);
        VL_IN8(flashMiso,0,0);
        VL_OUT8(flashClk,0,0);
        VL_OUT8(flashMosi,0,0);
        VL_OUT8(flashCs,0,0);
        VL_IN8(uart_rx,0,0);
        VL_OUT8(uart_tx,0,0);
        VL_IN8(btnDownL,0,0);
        VL_IN8(btnUpL,0,0);
        VL_IN8(btnLeftL,0,0);
        VL_IN8(btnRightL,0,0);
        VL_IN8(btnDownR,0,0);
        VL_IN8(btnUpR,0,0);
        VL_IN8(btnLeftR,0,0);
        VL_IN8(btnRightR,0,0);
        CData/*5:0*/ top__DOT__led;
        CData/*0:0*/ top__DOT__cpuclk;
        CData/*0:0*/ top__DOT__overflow;
        CData/*0:0*/ top__DOT__ren;
        CData/*1:0*/ top__DOT____Vcellout__cpu_1__debug_error;
        CData/*0:0*/ top__DOT__mem_ren;
        CData/*0:0*/ top__DOT__mem_wen;
        CData/*0:0*/ top__DOT__screen_wen;
        CData/*0:0*/ top__DOT__memReady;
        CData/*0:0*/ top__DOT__debug;
        CData/*0:0*/ top__DOT__second_stage_mem_ren;
        CData/*0:0*/ top__DOT__second_stage_mem_wen;
        CData/*0:0*/ top__DOT__program_mem_ren;
        CData/*0:0*/ top__DOT__program_mem_wen;
        CData/*0:0*/ top__DOT__uart_ren;
        CData/*0:0*/ top__DOT__uart_wen;
        CData/*0:0*/ top__DOT__usb_ren;
        CData/*0:0*/ top__DOT__clint_ren;
        CData/*0:0*/ top__DOT__clint_wen;
        CData/*0:0*/ top__DOT__mtimer_irq;
        CData/*0:0*/ top__DOT__btn_ren;
        CData/*0:0*/ top__DOT__btn_out;
        CData/*0:0*/ top__DOT__flash_ren;
        CData/*0:0*/ top__DOT__flash_wen;
        CData/*7:0*/ top__DOT__pixelData;
        CData/*0:0*/ top__DOT__error;
        CData/*4:0*/ top__DOT__R_tmp;
        CData/*5:0*/ top__DOT__G_tmp;
        CData/*4:0*/ top__DOT__B_tmp;
        CData/*2:0*/ top__DOT__state;
        CData/*0:0*/ top__DOT__counter27M;
        CData/*0:0*/ top__DOT__cpu_1__DOT__inA_is_PC;
        CData/*0:0*/ top__DOT__cpu_1__DOT__branch_taken;
        CData/*2:0*/ top__DOT__cpu_1__DOT__IDEX_funct3;
        CData/*6:0*/ top__DOT__cpu_1__DOT__IDEX_funct7;
        CData/*4:0*/ top__DOT__cpu_1__DOT__IDEX_instr_rs2;
        CData/*4:0*/ top__DOT__cpu_1__DOT__IDEX_instr_rs1;
        CData/*4:0*/ top__DOT__cpu_1__DOT__IDEX_instr_rd;
        CData/*0:0*/ top__DOT__cpu_1__DOT__IDEX_RegDst;
        CData/*0:0*/ top__DOT__cpu_1__DOT__IDEX_ALUSrc;
        CData/*0:0*/ top__DOT__cpu_1__DOT__IDEX_inA_is_PC;
    };
    struct {
        CData/*0:0*/ top__DOT__cpu_1__DOT__IDEX_Jump;
        CData/*0:0*/ top__DOT__cpu_1__DOT__IDEX_JumpJALR;
        CData/*1:0*/ top__DOT__cpu_1__DOT__IDEX_reg_type;
        CData/*2:0*/ top__DOT__cpu_1__DOT__IDEX_ALUcntrl;
        CData/*0:0*/ top__DOT__cpu_1__DOT__IDEX_MemRead;
        CData/*0:0*/ top__DOT__cpu_1__DOT__IDEX_MemWrite;
        CData/*0:0*/ top__DOT__cpu_1__DOT__IDEX_MemToReg;
        CData/*0:0*/ top__DOT__cpu_1__DOT__IDEX_RegWrite;
        CData/*2:0*/ top__DOT__cpu_1__DOT__EXMEM_funct3;
        CData/*2:0*/ top__DOT__cpu_1__DOT__MEMWB_funct3;
        CData/*4:0*/ top__DOT__cpu_1__DOT__EXMEM_RegWriteAddr;
        CData/*1:0*/ top__DOT__cpu_1__DOT__EXMEM_reg_type;
        CData/*0:0*/ top__DOT__cpu_1__DOT__EXMEM_Zero;
        CData/*0:0*/ top__DOT__cpu_1__DOT__EXMEM_JumpJALR;
        CData/*3:0*/ top__DOT__cpu_1__DOT__byte_select_vector;
        CData/*0:0*/ top__DOT__cpu_1__DOT__EXMEM_MemRead;
        CData/*0:0*/ top__DOT__cpu_1__DOT__EXMEM_MemWrite;
        CData/*0:0*/ top__DOT__cpu_1__DOT__EXMEM_RegWrite;
        CData/*0:0*/ top__DOT__cpu_1__DOT__EXMEM_MemToReg;
        CData/*4:0*/ top__DOT__cpu_1__DOT__MEMWB_RegWriteAddr;
        CData/*0:0*/ top__DOT__cpu_1__DOT__MEMWB_MemToReg;
        CData/*0:0*/ top__DOT__cpu_1__DOT__MEMWB_RegWrite;
        CData/*1:0*/ top__DOT__cpu_1__DOT__MEMWB_reg_type;
        CData/*0:0*/ top__DOT__cpu_1__DOT__RegDst;
        CData/*0:0*/ top__DOT__cpu_1__DOT__MemRead;
        CData/*0:0*/ top__DOT__cpu_1__DOT__MemWrite;
        CData/*0:0*/ top__DOT__cpu_1__DOT__MemToReg;
        CData/*0:0*/ top__DOT__cpu_1__DOT__ALUSrc;
        CData/*0:0*/ top__DOT__cpu_1__DOT__PCSrc;
        CData/*0:0*/ top__DOT__cpu_1__DOT__RegWrite;
        CData/*0:0*/ top__DOT__cpu_1__DOT__Jump;
        CData/*0:0*/ top__DOT__cpu_1__DOT__JumpJALR;
        CData/*1:0*/ top__DOT__cpu_1__DOT__reg_type;
        CData/*0:0*/ top__DOT__cpu_1__DOT__Branch;
        CData/*0:0*/ top__DOT__cpu_1__DOT__IDEX_Branch;
        CData/*0:0*/ top__DOT__cpu_1__DOT__EXMEM_Branch;
        CData/*0:0*/ top__DOT__cpu_1__DOT__bubble_ifid;
        CData/*0:0*/ top__DOT__cpu_1__DOT__bubble_idex;
        CData/*0:0*/ top__DOT__cpu_1__DOT__bubble_exmem;
        CData/*0:0*/ top__DOT__cpu_1__DOT__bubble_memwb;
        CData/*0:0*/ top__DOT__cpu_1__DOT__write_ifid;
        CData/*0:0*/ top__DOT__cpu_1__DOT__write_idex;
        CData/*0:0*/ top__DOT__cpu_1__DOT__write_exmem;
        CData/*0:0*/ top__DOT__cpu_1__DOT__write_memwb;
        CData/*0:0*/ top__DOT__cpu_1__DOT__write_pc;
        CData/*2:0*/ top__DOT__cpu_1__DOT__ALUcntrl;
        CData/*0:0*/ top__DOT__cpu_1__DOT__IDEX_csr_write_allowed;
        CData/*0:0*/ top__DOT__cpu_1__DOT__EXMEM_csr_write_allowed;
        CData/*0:0*/ top__DOT__cpu_1__DOT__MEMWB_csr_write_allowed;
        CData/*0:0*/ top__DOT__cpu_1__DOT__csr_immidiate;
        CData/*0:0*/ top__DOT__cpu_1__DOT__IDEX_csr_immidiate;
        CData/*0:0*/ top__DOT__cpu_1__DOT__EXMEM_csr_immidiate;
        CData/*0:0*/ top__DOT__cpu_1__DOT__MEMWB_csr_immidiate;
        CData/*3:0*/ top__DOT__cpu_1__DOT__ALUOp;
        CData/*1:0*/ top__DOT__cpu_1__DOT__bypassA;
        CData/*1:0*/ top__DOT__cpu_1__DOT__bypassB;
        CData/*0:0*/ top__DOT__cpu_1__DOT__keepDelayInstr;
        CData/*0:0*/ top__DOT__cpu_1__DOT__int_taken;
        CData/*0:0*/ top__DOT__cpu_1__DOT__syscall;
        CData/*0:0*/ top__DOT__cpu_1__DOT__trap_waiting;
        CData/*0:0*/ top__DOT__cpu_1__DOT__trap_in_ID;
        CData/*0:0*/ top__DOT__cpu_1__DOT__write_pc_delayed;
        CData/*0:0*/ top__DOT__cpu_1__DOT__bubble_ifid_delayed;
        CData/*0:0*/ top__DOT__cpu_1__DOT__pc_jumped;
    };
    struct {
        CData/*0:0*/ top__DOT__cpu_1__DOT__mepc_state;
        CData/*0:0*/ top__DOT__cpu_1__DOT__flushPipeline;
        CData/*2:0*/ top__DOT__cpu_1__DOT__csrFile__DOT__enableInterrupts;
        CData/*3:0*/ top__DOT__cpu_1__DOT__csrFile__DOT__pipeline_flush_count;
        CData/*0:0*/ top__DOT__cpu_1__DOT__control_stall_id__DOT__bubble_memwb;
        CData/*0:0*/ top__DOT__cpu_1__DOT__control_stall_id__DOT__memStalled;
        CData/*0:0*/ top__DOT__cpu_1__DOT__control_stall_id__DOT__suppressTrap;
        CData/*3:0*/ top__DOT__cpu_1__DOT__control_stall_id__DOT__state;
        CData/*1:0*/ top__DOT__cpu_1__DOT__control_bypass_ex__DOT__bypassA;
        CData/*1:0*/ top__DOT__cpu_1__DOT__control_bypass_ex__DOT__bypassB;
        CData/*7:0*/ top__DOT__cpu_1__DOT__mem_read_selector__DOT__byte_sel;
        CData/*0:0*/ top__DOT__bu__DOT__usb_ren;
        CData/*0:0*/ top__DOT__clint_inst__DOT__msip;
        CData/*1:0*/ top__DOT__mem__DOT__state;
        CData/*4:0*/ top__DOT__mem__DOT__cnt;
        CData/*0:0*/ top__DOT__mem__DOT__debug_reg;
        CData/*7:0*/ top__DOT__mem__DOT____Vlvbound_h32cf64f4__0;
        CData/*7:0*/ top__DOT__mem__DOT____Vlvbound_h32cddf14__0;
        CData/*7:0*/ top__DOT__mem__DOT____Vlvbound_h32d26f01__0;
        CData/*7:0*/ top__DOT__mem__DOT____Vlvbound_h32d0f0f5__0;
        CData/*0:0*/ top__DOT__bm__DOT__stableDownL;
        CData/*0:0*/ top__DOT__bm__DOT__stableUpL;
        CData/*0:0*/ top__DOT__bm__DOT__stableLeftL;
        CData/*0:0*/ top__DOT__bm__DOT__stableRightL;
        CData/*0:0*/ top__DOT__bm__DOT__stableDownR;
        CData/*0:0*/ top__DOT__bm__DOT__stableUpR;
        CData/*0:0*/ top__DOT__bm__DOT__stableLeftR;
        CData/*0:0*/ top__DOT__bm__DOT__stableRightR;
        CData/*1:0*/ top__DOT__bm__DOT__debounceDownL__DOT__state;
        CData/*0:0*/ top__DOT__bm__DOT__debounceDownL__DOT__btn_last;
        CData/*0:0*/ top__DOT__bm__DOT__debounceDownL__DOT__newChange;
        CData/*0:0*/ top__DOT__bm__DOT__debounceDownL__DOT__dff1;
        CData/*0:0*/ top__DOT__bm__DOT__debounceDownL__DOT__dff2;
        CData/*0:0*/ top__DOT__bm__DOT__debounceDownL__DOT__dff3;
        CData/*1:0*/ top__DOT__bm__DOT__debounceUpL__DOT__state;
        CData/*0:0*/ top__DOT__bm__DOT__debounceUpL__DOT__btn_last;
        CData/*0:0*/ top__DOT__bm__DOT__debounceUpL__DOT__newChange;
        CData/*0:0*/ top__DOT__bm__DOT__debounceUpL__DOT__dff1;
        CData/*0:0*/ top__DOT__bm__DOT__debounceUpL__DOT__dff2;
        CData/*0:0*/ top__DOT__bm__DOT__debounceUpL__DOT__dff3;
        CData/*1:0*/ top__DOT__bm__DOT__debounceLeftL__DOT__state;
        CData/*0:0*/ top__DOT__bm__DOT__debounceLeftL__DOT__btn_last;
        CData/*0:0*/ top__DOT__bm__DOT__debounceLeftL__DOT__newChange;
        CData/*0:0*/ top__DOT__bm__DOT__debounceLeftL__DOT__dff1;
        CData/*0:0*/ top__DOT__bm__DOT__debounceLeftL__DOT__dff2;
        CData/*0:0*/ top__DOT__bm__DOT__debounceLeftL__DOT__dff3;
        CData/*1:0*/ top__DOT__bm__DOT__debounceRightL__DOT__state;
        CData/*0:0*/ top__DOT__bm__DOT__debounceRightL__DOT__btn_last;
        CData/*0:0*/ top__DOT__bm__DOT__debounceRightL__DOT__newChange;
        CData/*0:0*/ top__DOT__bm__DOT__debounceRightL__DOT__dff1;
        CData/*0:0*/ top__DOT__bm__DOT__debounceRightL__DOT__dff2;
        CData/*0:0*/ top__DOT__bm__DOT__debounceRightL__DOT__dff3;
        CData/*1:0*/ top__DOT__bm__DOT__debounceDownR__DOT__state;
        CData/*0:0*/ top__DOT__bm__DOT__debounceDownR__DOT__btn_last;
        CData/*0:0*/ top__DOT__bm__DOT__debounceDownR__DOT__newChange;
        CData/*0:0*/ top__DOT__bm__DOT__debounceDownR__DOT__dff1;
        CData/*0:0*/ top__DOT__bm__DOT__debounceDownR__DOT__dff2;
        CData/*0:0*/ top__DOT__bm__DOT__debounceDownR__DOT__dff3;
        CData/*1:0*/ top__DOT__bm__DOT__debounceUpR__DOT__state;
        CData/*0:0*/ top__DOT__bm__DOT__debounceUpR__DOT__btn_last;
        CData/*0:0*/ top__DOT__bm__DOT__debounceUpR__DOT__newChange;
        CData/*0:0*/ top__DOT__bm__DOT__debounceUpR__DOT__dff1;
        CData/*0:0*/ top__DOT__bm__DOT__debounceUpR__DOT__dff2;
        CData/*0:0*/ top__DOT__bm__DOT__debounceUpR__DOT__dff3;
    };
    struct {
        CData/*1:0*/ top__DOT__bm__DOT__debounceLeftR__DOT__state;
        CData/*0:0*/ top__DOT__bm__DOT__debounceLeftR__DOT__btn_last;
        CData/*0:0*/ top__DOT__bm__DOT__debounceLeftR__DOT__newChange;
        CData/*0:0*/ top__DOT__bm__DOT__debounceLeftR__DOT__dff1;
        CData/*0:0*/ top__DOT__bm__DOT__debounceLeftR__DOT__dff2;
        CData/*0:0*/ top__DOT__bm__DOT__debounceLeftR__DOT__dff3;
        CData/*1:0*/ top__DOT__bm__DOT__debounceRightR__DOT__state;
        CData/*0:0*/ top__DOT__bm__DOT__debounceRightR__DOT__btn_last;
        CData/*0:0*/ top__DOT__bm__DOT__debounceRightR__DOT__newChange;
        CData/*0:0*/ top__DOT__bm__DOT__debounceRightR__DOT__dff1;
        CData/*0:0*/ top__DOT__bm__DOT__debounceRightR__DOT__dff2;
        CData/*0:0*/ top__DOT__bm__DOT__debounceRightR__DOT__dff3;
        CData/*0:0*/ top__DOT__flashController__DOT__flash_enable;
        CData/*0:0*/ top__DOT__flashController__DOT__flash_wen;
        CData/*0:0*/ top__DOT__flashController__DOT__flash_ren;
        CData/*0:0*/ top__DOT__flashController__DOT__flash_ready;
        CData/*4:0*/ top__DOT__flashController__DOT__stateDebug;
        CData/*7:0*/ top__DOT__flashController__DOT__navigator__DOT__currentByteOut;
        CData/*7:0*/ top__DOT__flashController__DOT__navigator__DOT__currentByteNum;
        CData/*0:0*/ top__DOT__flashController__DOT__navigator__DOT__enabling_done;
        CData/*3:0*/ top__DOT__flashController__DOT__navigator__DOT__state;
        CData/*3:0*/ top__DOT__flashController__DOT__navigator__DOT__returnState;
        CData/*0:0*/ top__DOT__flashController__DOT__navigator__DOT__dataReady;
        CData/*0:0*/ top__DOT__flashController__DOT__navigator__DOT__write_progress;
        CData/*0:0*/ top__DOT__SecondStageRAM__DOT__debug_reg;
        CData/*0:0*/ top__DOT__RAM__DOT__debug_reg;
        CData/*0:0*/ top__DOT__ppu_inst__DOT__textEn;
        CData/*0:0*/ top__DOT__ppu_inst__DOT__spritesEn;
        CData/*7:0*/ top__DOT__ppu_inst__DOT__writeAttr;
        CData/*7:0*/ top__DOT__ppu_inst__DOT__writeText;
        CData/*7:0*/ top__DOT__ppu_inst__DOT__writeSprite;
        CData/*7:0*/ top__DOT__ppu_inst__DOT__dataOutTxt;
        CData/*7:0*/ top__DOT__ppu_inst__DOT__dataOutAttr;
        CData/*7:0*/ top__DOT__ppu_inst__DOT__dataOutSprite;
        CData/*6:0*/ top__DOT__ppu_inst__DOT__spriteID;
        CData/*0:0*/ top__DOT__ppu_inst__DOT__hblank;
        CData/*7:0*/ top__DOT__ppu_inst__DOT__r;
        CData/*7:0*/ top__DOT__ppu_inst__DOT__g;
        CData/*7:0*/ top__DOT__ppu_inst__DOT__b;
        CData/*4:0*/ top__DOT__ppu_inst__DOT__cur_sprite_buf;
        CData/*0:0*/ top__DOT__ppu_inst__DOT__hasStarted;
        CData/*7:0*/ top__DOT__ppu_inst__DOT____Vlvbound_hef58082d__0;
        CData/*7:0*/ top__DOT__ppu_inst__DOT____Vlvbound_hef58852e__0;
        CData/*7:0*/ top__DOT__ppu_inst__DOT__text_Buffer__DOT__din_b;
        CData/*7:0*/ top__DOT__ppu_inst__DOT__text_Buffer__DOT__dout_a;
        CData/*7:0*/ top__DOT__ppu_inst__DOT__attributes_Buffer__DOT__din_b;
        CData/*7:0*/ top__DOT__ppu_inst__DOT__attributes_Buffer__DOT__dout_a;
        CData/*7:0*/ top__DOT__ppu_inst__DOT__sprite_BRAM__DOT__din_b;
        CData/*7:0*/ top__DOT__ppu_inst__DOT__sprite_BRAM__DOT__dout_a;
        CData/*7:0*/ top__DOT__VGA__DOT__dataOutTxt;
        CData/*7:0*/ top__DOT__VGA__DOT__dataOutAttr;
        CData/*7:0*/ top__DOT__text__DOT____Vlvbound_h835a9cca__0;
        CData/*7:0*/ top__DOT__text__DOT____Vlvbound_h5244a299__0;
        CData/*7:0*/ top__DOT__uart_controller__DOT__data_in;
        CData/*7:0*/ top__DOT__uart_controller__DOT__byte_out;
        CData/*0:0*/ top__DOT__uart_controller__DOT__rx_rdy;
        CData/*0:0*/ top__DOT__uart_controller__DOT__tx_busy;
        CData/*7:0*/ top__DOT__uart_controller__DOT__rx_data;
        CData/*7:0*/ top__DOT__uart_controller__DOT__tx_data;
        CData/*0:0*/ top__DOT__uart_controller__DOT__ena_tx;
        CData/*7:0*/ top__DOT__uart_controller__DOT__ier;
        CData/*7:0*/ top__DOT__uart_controller__DOT__lcr;
        CData/*7:0*/ top__DOT__uart_controller__DOT__lsr;
        CData/*7:0*/ top__DOT__uart_controller__DOT__dll;
    };
    struct {
        CData/*7:0*/ top__DOT__uart_controller__DOT__dlm;
        CData/*0:0*/ top__DOT__uart_controller__DOT__dlab;
        CData/*0:0*/ top__DOT__uart_controller__DOT__uart_inst__DOT__rx_sample_pulse;
        CData/*3:0*/ top__DOT__uart_controller__DOT__uart_inst__DOT__rx_position;
        CData/*0:0*/ top__DOT__uart_controller__DOT__uart_inst__DOT__rxd_reg;
        CData/*0:0*/ top__DOT__uart_controller__DOT__uart_inst__DOT__last_rxd;
        CData/*0:0*/ top__DOT__uart_controller__DOT__uart_inst__DOT__rx_busy;
        CData/*0:0*/ top__DOT__uart_controller__DOT__uart_inst__DOT__rx_last_busy;
        CData/*3:0*/ top__DOT__uart_controller__DOT__uart_inst__DOT__tx_position;
        CData/*7:0*/ top__DOT__uart_controller__DOT__uart_inst__DOT__tx_data_reg;
        CData/*0:0*/ top__DOT__uart_controller__DOT__uart_inst__DOT__tx_run;
        CData/*0:0*/ top__DOT__uart_controller__DOT__uart_inst__DOT__rx_trigger;
        CData/*2:0*/ __Vdly__top__DOT__state;
        CData/*0:0*/ __Vdly__top__DOT__flashController__DOT__flash_ready;
        CData/*3:0*/ __Vdly__top__DOT__flashController__DOT__navigator__DOT__state;
        CData/*7:0*/ __Vdly__top__DOT__flashController__DOT__navigator__DOT__currentByteNum;
        CData/*7:0*/ __Vdly__top__DOT__flashController__DOT__navigator__DOT__currentByteOut;
        CData/*0:0*/ __Vdly__top__DOT__flashController__DOT__navigator__DOT__enabling_done;
        CData/*3:0*/ __Vdly__top__DOT__flashController__DOT__navigator__DOT__returnState;
        CData/*0:0*/ __Vdly__top__DOT__uart_controller__DOT__uart_inst__DOT__rx_busy;
        CData/*3:0*/ __Vdly__top__DOT__uart_controller__DOT__uart_inst__DOT__rx_position;
        CData/*0:0*/ __Vdly__top__DOT__ppu_inst__DOT__hblank;
        CData/*4:0*/ __VdlyDim0__top__DOT__ppu_inst__DOT__objectAttributes__v0;
        CData/*0:0*/ __VdlySet__top__DOT__ppu_inst__DOT__objectAttributes__v0;
        CData/*7:0*/ __VdlyVal__top__DOT__ppu_inst__DOT__lineBuffer__v0;
        CData/*4:0*/ __VdlyDim0__top__DOT__ppu_inst__DOT__lineBuffer__v0;
        CData/*0:0*/ __VdlySet__top__DOT__ppu_inst__DOT__lineBuffer__v0;
        CData/*7:0*/ __VdlyVal__top__DOT__ppu_inst__DOT__lineBuffer__v1;
        CData/*4:0*/ __VdlyDim0__top__DOT__ppu_inst__DOT__lineBuffer__v1;
        CData/*0:0*/ __VdlySet__top__DOT__ppu_inst__DOT__lineBuffer__v1;
        CData/*0:0*/ __VdlySet__top__DOT__ppu_inst__DOT__lineBuffer__v2;
        CData/*7:0*/ __VdlyVal__top__DOT__ppu_inst__DOT__text_Buffer__DOT__mem__v0;
        CData/*0:0*/ __VdlySet__top__DOT__ppu_inst__DOT__text_Buffer__DOT__mem__v0;
        CData/*7:0*/ __VdlyVal__top__DOT__ppu_inst__DOT__attributes_Buffer__DOT__mem__v0;
        CData/*0:0*/ __VdlySet__top__DOT__ppu_inst__DOT__attributes_Buffer__DOT__mem__v0;
        CData/*7:0*/ __VdlyVal__top__DOT__ppu_inst__DOT__sprite_BRAM__DOT__mem__v0;
        CData/*0:0*/ __VdlySet__top__DOT__ppu_inst__DOT__sprite_BRAM__DOT__mem__v0;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__top__DOT__reset__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        SData/*9:0*/ top__DOT__pixelAddress;
        SData/*13:0*/ top__DOT__xcursor;
        SData/*13:0*/ top__DOT__ycursor;
        SData/*11:0*/ top__DOT__cpu_1__DOT__IDEX_csr_addr;
        SData/*11:0*/ top__DOT__cpu_1__DOT__EXMEM_csr_addr;
        SData/*11:0*/ top__DOT__cpu_1__DOT__MEMWB_csr_addr;
        SData/*15:0*/ top__DOT__cpu_1__DOT__mem_read_selector__DOT__half;
        SData/*8:0*/ top__DOT__flashController__DOT__navigator__DOT__bitsToSend;
        SData/*14:0*/ top__DOT__ppu_inst__DOT__spritePointer;
        SData/*9:0*/ top__DOT__ppu_inst__DOT__objectPointer;
        SData/*15:0*/ top__DOT__ppu_inst__DOT__data_in_half;
        SData/*10:0*/ top__DOT__ppu_inst__DOT____Vcellinp__attributes_Buffer__addr_b;
        SData/*8:0*/ top__DOT__ppu_inst__DOT__buffer_counter;
        SData/*15:0*/ top__DOT__ppu_inst__DOT__obj_line_buffer;
        SData/*14:0*/ top__DOT__VGA__DOT__currentPixel;
        SData/*15:0*/ top__DOT__uart_controller__DOT__uart_inst__DOT__rx_period;
        SData/*9:0*/ top__DOT__uart_controller__DOT__uart_inst__DOT__rx_byte;
        SData/*15:0*/ top__DOT__uart_controller__DOT__uart_inst__DOT__tx_period;
        SData/*9:0*/ top__DOT__uart_controller__DOT__uart_inst__DOT__tx_byte;
        SData/*10:0*/ top__DOT__counter1mhz__DOT__subCounter;
        SData/*10:0*/ top__DOT__counter50mhz__DOT__subCounter;
    };
    struct {
        SData/*8:0*/ __Vdly__top__DOT__flashController__DOT__navigator__DOT__bitsToSend;
        SData/*15:0*/ __Vdly__top__DOT__uart_controller__DOT__uart_inst__DOT__rx_period;
        SData/*9:0*/ __Vdly__top__DOT__uart_controller__DOT__uart_inst__DOT__rx_byte;
        SData/*9:0*/ __Vdly__top__DOT__ppu_inst__DOT__objectPointer;
        SData/*13:0*/ __Vdly__top__DOT__ycursor;
        SData/*13:0*/ __Vdly__top__DOT__xcursor;
        SData/*10:0*/ __VdlyDim0__top__DOT__ppu_inst__DOT__text_Buffer__DOT__mem__v0;
        SData/*10:0*/ __VdlyDim0__top__DOT__ppu_inst__DOT__attributes_Buffer__DOT__mem__v0;
        SData/*13:0*/ __VdlyDim0__top__DOT__ppu_inst__DOT__sprite_BRAM__DOT__mem__v0;
        SData/*13:0*/ __Vtrigprevexpr___TOP__top__DOT__xcursor__0;
        SData/*13:0*/ __Vtrigprevexpr___TOP__top__DOT__ycursor__0;
        IData/*31:0*/ top__DOT__instr;
        IData/*31:0*/ top__DOT__data_addr;
        IData/*31:0*/ top__DOT__data_read;
        IData/*31:0*/ top__DOT__boot_data_out;
        IData/*31:0*/ top__DOT__boot_instr;
        IData/*31:0*/ top__DOT__second_stage_instr;
        IData/*31:0*/ top__DOT__second_stage_mem_out;
        IData/*31:0*/ top__DOT__program_instr;
        IData/*31:0*/ top__DOT__program_mem_out;
        IData/*31:0*/ top__DOT__usb_data_out;
        IData/*31:0*/ top__DOT__clint_data_out;
        IData/*31:0*/ top__DOT__flash_data_out;
        IData/*31:0*/ top__DOT__counter1M;
        IData/*31:0*/ top__DOT__counter50M;
        IData/*22:0*/ top__DOT__txCounter;
        IData/*23:0*/ top__DOT__counter;
        IData/*31:0*/ top__DOT__cpu_1__DOT__IFID_instr;
        IData/*31:0*/ top__DOT__cpu_1__DOT__PC_IF2;
        IData/*31:0*/ top__DOT__cpu_1__DOT__PC;
        IData/*31:0*/ top__DOT__cpu_1__DOT__PC_OLD;
        IData/*31:0*/ top__DOT__cpu_1__DOT__IFID_PC;
        IData/*31:0*/ top__DOT__cpu_1__DOT__IDEX_PC;
        IData/*31:0*/ top__DOT__cpu_1__DOT__EXMEM_PC;
        IData/*31:0*/ top__DOT__cpu_1__DOT__MEMWB_PC;
        IData/*31:0*/ top__DOT__cpu_1__DOT__PCplus4;
        IData/*31:0*/ top__DOT__cpu_1__DOT__PC_new;
        IData/*31:0*/ top__DOT__cpu_1__DOT__IDEX_instr;
        IData/*31:0*/ top__DOT__cpu_1__DOT__EXMEM_instr;
        IData/*31:0*/ top__DOT__cpu_1__DOT__MEMWB_instr;
        IData/*31:0*/ top__DOT__cpu_1__DOT__delayed_instr;
        IData/*31:0*/ top__DOT__cpu_1__DOT__IDEX_signExtend;
        IData/*31:0*/ top__DOT__cpu_1__DOT__signExtend;
        IData/*31:0*/ top__DOT__cpu_1__DOT__IDEX_rdA;
        IData/*31:0*/ top__DOT__cpu_1__DOT__IDEX_rdB;
        IData/*31:0*/ top__DOT__cpu_1__DOT__EXMEM_ALUOut;
        IData/*31:0*/ top__DOT__cpu_1__DOT__EXMEM_BranchALUOut;
        IData/*31:0*/ top__DOT__cpu_1__DOT__EXMEM_MemWriteData;
        IData/*31:0*/ top__DOT__cpu_1__DOT__MemWriteData;
        IData/*31:0*/ top__DOT__cpu_1__DOT__MEMWB_DMemOut;
        IData/*31:0*/ top__DOT__cpu_1__DOT__MEMWB_ALUOut;
        IData/*31:0*/ top__DOT__cpu_1__DOT__ALUInA;
        IData/*31:0*/ top__DOT__cpu_1__DOT__ALUInB;
        IData/*31:0*/ top__DOT__cpu_1__DOT__bypassOutA;
        IData/*31:0*/ top__DOT__cpu_1__DOT__bypassOutB;
        IData/*31:0*/ top__DOT__cpu_1__DOT__MemOut;
        IData/*31:0*/ top__DOT__cpu_1__DOT__wRegData;
        IData/*31:0*/ top__DOT__cpu_1__DOT__WB_csr_data;
        IData/*31:0*/ top__DOT__cpu_1__DOT__csr_data;
        IData/*31:0*/ top__DOT__cpu_1__DOT__EXMEM_csr_data;
        IData/*31:0*/ top__DOT__cpu_1__DOT__MEMWB_csr_data;
        IData/*31:0*/ top__DOT__cpu_1__DOT__imm_i;
        IData/*31:0*/ top__DOT__cpu_1__DOT__trap_vector;
        VlWide<5>/*159:0*/ top__DOT__cpu_1__DOT__debug_str;
    };
    struct {
        IData/*31:0*/ top__DOT__cpu_1__DOT__PCPrevious;
        IData/*31:0*/ top__DOT__cpu_1__DOT__newmepc;
        VlWide<64>/*2039:0*/ top__DOT__cpu_1__DOT__pc_string;
        IData/*31:0*/ top__DOT__cpu_1__DOT__cpu_regs__DOT__i;
        IData/*31:0*/ top__DOT__cpu_1__DOT__csrFile__DOT__i;
        IData/*31:0*/ top__DOT__cpu_1__DOT__csrFile__DOT__mstatus;
        IData/*31:0*/ top__DOT__cpu_1__DOT__csrFile__DOT__mstatush;
        IData/*31:0*/ top__DOT__cpu_1__DOT__csrFile__DOT__misa;
        IData/*31:0*/ top__DOT__cpu_1__DOT__csrFile__DOT__mie;
        IData/*31:0*/ top__DOT__cpu_1__DOT__csrFile__DOT__mtvec;
        IData/*31:0*/ top__DOT__cpu_1__DOT__csrFile__DOT__mscratch;
        IData/*31:0*/ top__DOT__cpu_1__DOT__csrFile__DOT__mepc;
        IData/*31:0*/ top__DOT__cpu_1__DOT__csrFile__DOT__mcause;
        IData/*31:0*/ top__DOT__cpu_1__DOT__csrFile__DOT__mtval;
        IData/*31:0*/ top__DOT__cpu_1__DOT__csrFile__DOT__mip;
        VlWide<10>/*319:0*/ top__DOT__cpu_1__DOT__csrFile__DOT__debug;
        VlWide<10>/*319:0*/ top__DOT__cpu_1__DOT__csrFile__DOT__debug2;
        IData/*31:0*/ top__DOT__cpu_1__DOT__csrFile__DOT__trap_vector_reg;
        IData/*31:0*/ top__DOT__cpu_1__DOT__cpu_alu__DOT__out_val;
        IData/*31:0*/ top__DOT__bu__DOT__usb_out;
        IData/*31:0*/ top__DOT__mem__DOT__i;
        IData/*19:0*/ top__DOT__mem__DOT__saved_data_addr;
        IData/*31:0*/ top__DOT__mem__DOT____Vlvbound_h03e4b710__0;
        IData/*21:0*/ top__DOT__bm__DOT__debounceDownL__DOT__counter;
        IData/*21:0*/ top__DOT__bm__DOT__debounceUpL__DOT__counter;
        IData/*21:0*/ top__DOT__bm__DOT__debounceLeftL__DOT__counter;
        IData/*21:0*/ top__DOT__bm__DOT__debounceRightL__DOT__counter;
        IData/*21:0*/ top__DOT__bm__DOT__debounceDownR__DOT__counter;
        IData/*21:0*/ top__DOT__bm__DOT__debounceUpR__DOT__counter;
        IData/*21:0*/ top__DOT__bm__DOT__debounceLeftR__DOT__counter;
        IData/*21:0*/ top__DOT__bm__DOT__debounceRightR__DOT__counter;
        IData/*23:0*/ top__DOT__flashController__DOT__flash_address;
        IData/*31:0*/ top__DOT__flashController__DOT__flash_data_in;
        IData/*31:0*/ top__DOT__flashController__DOT__flash_data_out;
        VlWide<8>/*255:0*/ top__DOT__flashController__DOT__navigator__DOT__dataIn;
        VlWide<8>/*255:0*/ top__DOT__flashController__DOT__navigator__DOT__dataInBuffer;
        IData/*23:0*/ top__DOT__flashController__DOT__navigator__DOT__dataToSend;
        IData/*31:0*/ top__DOT__SecondStageRAM__DOT__i;
        IData/*31:0*/ top__DOT__RAM__DOT__i;
        IData/*31:0*/ top__DOT__ppu_inst__DOT__text_address;
        IData/*31:0*/ top__DOT__ppu_inst__DOT__i;
        IData/*31:0*/ top__DOT__ppu_inst__DOT____Vlvbound_h4cbb62ca__0;
        VlWide<4>/*127:0*/ top__DOT__VGA__DOT__charMem;
        IData/*31:0*/ top__DOT__text__DOT__i;
        IData/*31:0*/ top__DOT__text__DOT__j;
        IData/*22:0*/ __Vdly__top__DOT__txCounter;
        IData/*23:0*/ __Vdly__top__DOT__flashController__DOT__navigator__DOT__dataToSend;
        VlWide<8>/*255:0*/ __Vdly__top__DOT__flashController__DOT__navigator__DOT__dataIn;
        IData/*31:0*/ __VdlyVal__top__DOT__ppu_inst__DOT__objectAttributes__v0;
        IData/*31:0*/ __VactIterCount;
        QData/*63:0*/ top__DOT__cpu_1__DOT__cpu_alu__DOT__debug_string;
        QData/*63:0*/ top__DOT__cpu_1__DOT__control_alu__DOT__debug_string;
        QData/*63:0*/ top__DOT__clint_inst__DOT__mtime;
        QData/*63:0*/ top__DOT__clint_inst__DOT__mtimecmp;
        QData/*32:0*/ top__DOT__flashController__DOT__navigator__DOT__counter;
        QData/*32:0*/ __Vdly__top__DOT__flashController__DOT__navigator__DOT__counter;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__cpu_1__DOT__cpu_regs__DOT__data;
        VlUnpacked<IData/*31:0*/, 8194> top__DOT__mem__DOT__data_mem;
        VlUnpacked<CData/*7:0*/, 4> top__DOT__flashController__DOT__navigator__DOT__stored_characters;
        VlUnpacked<IData/*31:0*/, 262144> top__DOT__SecondStageRAM__DOT__data_mem;
        VlUnpacked<IData/*31:0*/, 262144> top__DOT__RAM__DOT__data_mem;
        VlUnpacked<IData/*31:0*/, 20> top__DOT__ppu_inst__DOT__objectAttributes;
        VlUnpacked<SData/*15:0*/, 20> top__DOT__ppu_inst__DOT__lineBuffer;
        VlUnpacked<CData/*7:0*/, 2048> top__DOT__ppu_inst__DOT__text_Buffer__DOT__mem;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 2048> top__DOT__ppu_inst__DOT__attributes_Buffer__DOT__mem;
        VlUnpacked<CData/*7:0*/, 16384> top__DOT__ppu_inst__DOT__sprite_BRAM__DOT__mem;
        VlUnpacked<VlWide<16>/*511:0*/, 20> top__DOT__text__DOT__charMemory;
        VlUnpacked<CData/*0:0*/, 8> __Vm_traceActivity;
    };
    VlNBACommitQueue<VlUnpacked<VlWide<16>/*511:0*/, 20>, true, VlWide<16>/*511:0*/, 1> __VdlyCommitQueuetop__DOT__text__DOT__charMemory;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<4> __VactTriggered;
    VlTriggerVec<4> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
