-d C:\Users\Panagiotis\Downloads\iordanaScreen\RISCV\impl\gwsynthesis\RISCV.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\Panagiotis\Downloads\iordanaScreen\RISCV\src\tangnano9k.cst
-cfg C:\Users\Panagiotis\Downloads\iordanaScreen\RISCV\impl\pnr\device.cfg
-sdc C:\Users\Panagiotis\Downloads\iordanaScreen\RISCV\src\Tang_nano_9K_LCD.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 2
-route_option 1
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
